earthquake_queries = [
    "What is an earthquake?",
    "What causes earthquakes?",
    "What is the Richter scale?",
    "What is an aftershock?",
    "What is seismic activity?",
    "What should I do during an earthquake?",
    "How do I evacuate safely during an earthquake?",
    "Where should I take cover?",
    "Should I run outside?",
    "What is Drop, Cover, and Hold On?",
    "What if I'm in class?",
    "What if I'm in the washroom?",
    "What if I'm on the top floor?",
    "What if I'm in the library?",
    "What if I'm in the hostel?",
    "What if I'm in a wheelchair?",
    "What if the power goes out?",
    "What if the stairs are blocked?",
    "What if the exit is locked?",
    "How do I help others evacuate?",
    "What should I do after the shaking stops?",
    "How do I stay calm during an earthquake?",
    "What if someone is injured?",
    "Should I wait for instructions?",
    "What if I'm outside when it starts?",
    "Can I go back inside?",
    "What should I pack in an earthquake kit?",
    "What are the emergency numbers?",
    "How do I check if the building is safe?",
    "What should I do if there's an aftershock?",
    "How do I help younger students?",
    "Can I use my phone flashlight?",
    "How do I report damage?",
    "What if I'm in the playground?",
    "What if I'm in the cafeteria?",
    "What if I'm in the auditorium?",
    "What if I'm in the lab?",
    "What if I'm in the hostel at night?",
    "What if the alarm doesn't go off?",
    "What if the building is old?",
    "What if the ceiling starts cracking?",
    "What if windows shatter?",
    "What if furniture falls?",
    "What if I'm under a table?",
    "What if I'm near glass?",
    "What if I'm in a crowded hallway?",
    "What if I'm alone?",
    "What if my phone battery is low?",
    "What if I can't find my group?",
    "What if I panic?",
    "What if I lose my ID?",
    "What if I can't reach my parents?",
    "What if my shoes are missing?",
    "What if my bag is heavy?",
    "What if I have asthma?",
    "What if I wear glasses?",
    "What if I have a disability?",
    "What if I can't speak the local language?",
    "What if I need medication?",
    "What if I have exams?",
    "What if I miss attendance?",
    "What if I lose my books?",
    "What if my uniform gets torn?",
    "What if I get stuck in a lift?",
    "What if I hear strange noises?",
    "What if I see cracks in the wall?",
    "What if the ground shakes again?",
    "What if I feel dizzy?",
    "What if I faint?",
    "What if I see someone crying?",
    "What if I see someone injured?",
    "What if I see fire after the quake?",
    "What if I smell gas?",
    "What if I see water leaking?",
    "What if I see sparks?",
    "What if I can't open the door?",
    "What if I can't breathe?",
    "What if I feel trapped?",
    "What if I hear sirens?",
    "What if I hear announcements?",
    "What if I see rescue teams?",
    "What if I see fallen trees?",
    "What if I see broken wires?",
    "What if I see collapsed walls?",
    "What if I see broken glass?",
    "What if I see panic around me?",
    "What if I see someone helping?",
    "What if I see someone shouting?",
    "What if I hear loud noises?",
    "What if I see dust clouds?",
    "What if I see falling debris?",
    "What if I see people running?",
    "What if I see blocked roads?",
    "What if I see damaged vehicles?",
    "What if I see broken pipes?",
    "What if I see water flooding?",
    "What if I see fire trucks?",
    "What if I see police?",
    "What if I see ambulances?",
    "What should I do during an earthquake?",
    "Bhukamp ke time kya karna chahiye?",
    "Earthquake aane par kya karein?",
    "Bhukamp ke samay safe jagah kaise dhundhein?",
    "Drop, Cover, Hold On ka matlab kya hai?",
]


flood_queries = [
    "What is a flood?",
    "What causes floods?",
    "What is flash flooding?",
    "What is urban flooding?",
    "What is a floodplain?",
    "What is a flood warning?",
    "What is a flood alert?",
    "What is a dam burst?",
    "What is river overflow?",
    "What is storm surge?",
    "What is waterlogging?",
    "What is monsoon flooding?",
    "What should I do during a flood?",
    "How do I evacuate safely?",
    "Should I walk through flood water?",
    "Should I stay inside?",
    "What if water enters the classroom?",
    "What if I'm in the hostel?",
    "What if I'm stuck in school?",
    "What if the roads are flooded?",
    "What if the water level rises quickly?",
    "What if I'm separated from my group?",
    "Should I climb to higher ground?",
    "Should I unplug electrical devices?",
    "Should I drink tap water?",
    "Should I use public transport?",
    "Should I go back to get my books?",
    "Should I touch submerged wires?",
    "Should I wade through water?",
    "What if I’m in the playground?",
    "What if I’m in the lab?",
    "What if I’m in the library?",
    "What if I’m in the washroom?",
    "What if I’m in the auditorium?",
    "What if I’m in the cafeteria?",
    "What if I’m in the hostel at night?",
    "What if I’m on the top floor?",
    "What if I’m in a basement?",
    "What if I’m outside?",
    "What if I’m in a vehicle?",
    "What if I’m near a river?",
    "What if I’m near a drain?",
    "What if I’m near a canal?",
    "What if I’m near a bridge?",
    "What if I’m near a dam?",
    "What if I’m near a water tank?",
    "What if I’m near a pond?",
    "What if I’m near a lake?",
    "What if I’m near a waterfall?",
    "What if I’m near a storm?",
    "What if I’m near lightning?",
    "What if I’m near thunder?",
    "What if I’m near strong winds?",
    "What if I’m near flying debris?",
    "What if I’m near broken trees?",
    "What if I’m near fallen wires?",
    "What if I’m near broken poles?",
    "What if I’m near blocked roads?",
    "What if I’m near damaged buildings?",
    "What if I’m near collapsed walls?",
    "What if I’m near broken glass?",
    "What if I’m near panic?",
    "What if I’m near rescue teams?",
    "What if I’m near fire trucks?",
    "What if I’m near police?",
    "What if I’m near ambulances?",
]

fire_queries = [
    
    "What is a fire?",
    "What causes fire?",
    "What is a fire hazard?",
    "What is a fire drill?",
    "What is a fire extinguisher?",
    "What is a fire alarm?",
    "What is a smoke detector?",
    "What is a fire exit?",
    "What is a fire escape plan?",
    "What is a fire triangle?",
    "What is combustion?",
    "What is flammable material?",
    "What should I do during a fire?",
    "How do I evacuate safely?",
    "Should I use the elevator?",
    "Should I break a window?",
    "What if the exit is blocked?",
    "How do I help someone who is unconscious?",
    "Should we wait for instructions or evacuate?",
    "What if I panic and forget the drill?",
    "Can I use my phone flashlight?",
    "What if the power goes out?",
    "How do we stay calm during a fire?",
    "What if I’m in a wheelchair?",
    "What if I’m responsible for younger students?",
    "What if I’m in the hostel at night?",
    "What if I hear sirens but no announcements?",
    "Can I go back to get my bag?",
    "What if I lose my ID during evacuation?",
    "What if my shoes are missing?",
    "What if I have asthma?",
    "What if I wear glasses?",
    "What if I need medication?",
    "What if I don’t speak the local language?",
    "What if I faint?",
    "What if I see someone crying?",
    "What if I see flames?",
    "What if I see smoke everywhere?",
    "What if I see broken wires?",
    "What if I see collapsed walls?",
    "What if I see broken glass?",
    "What if I see people running?",
    "What if I see blocked roads?",
    "What if I see damaged vehicles?",
    "What are the emergency numbers for fire?",
    "How do I report a fire?",
    "How do I help someone who is unconscious?",
    "What should I pack in a fire kit?",
    "How do I know when it’s safe to return?"

]




def enrich_student_query(user_input):
    for query in earthquake_queries:
        if query.lower() in user_input.lower():
            return "You are asking about earthquake safety."
    for query in flood_queries:
        if query.lower() in user_input.lower():
            return "You are asking about flood safety."
    for query in fire_queries:
        if query.lower() in user_input.lower():
            return "You are asking about fire safety."
    return "General disaster safety guidance."
